"""Self-contained HTML report (Jinja2, inline template to avoid package-data config).
PDF export (WeasyPrint) lands in Week 9 as an optional extra.
"""
from __future__ import annotations

from jinja2 import BaseLoader, Environment, select_autoescape

from ..schemas.scan import ScanResult

_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>VibeTest report — {{ result.target_url }}</title>
<style>
  body { font-family: system-ui, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; color: #1a1a1a; }
  h1 { font-size: 1.4rem; }
  .meta { color: #666; font-size: 0.9rem; margin-bottom: 2rem; }
  .finding { border: 1px solid #ddd; border-left: 6px solid #999; border-radius: 6px; padding: 1rem; margin-bottom: 1rem; }
  .sev-critical { border-left-color: #b00020; }
  .sev-high { border-left-color: #d32f2f; }
  .sev-medium { border-left-color: #f9a825; }
  .sev-low { border-left-color: #0277bd; }
  .sev-info { border-left-color: #9e9e9e; }
  .badge { display: inline-block; padding: 0.1rem 0.5rem; border-radius: 4px; background: #eee; font-size: 0.8rem; text-transform: uppercase; }
  .evidence { background: #f7f7f7; padding: 0.5rem; border-radius: 4px; font-family: monospace; font-size: 0.85rem; margin: 0.25rem 0; }
  .explanation { white-space: pre-wrap; }
</style>
</head>
<body>
<h1>VibeTest security report</h1>
<div class="meta">
  Target: <strong>{{ result.target_url }}</strong><br>
  Scanned: {{ result.started_at }}<br>
  Findings: {{ result.findings | length }}
  {% set tech = result.artifact.tech %}
  {% set known = ([tech.framework, tech.hosting] + tech.backend_services) | select | list %}
  {% if known %}<br>Detected technology: {{ known | join(' · ') }}{% endif %}
</div>
{% for f in result.findings %}
<div class="finding sev-{{ f.severity.value }}">
  <span class="badge">{{ f.severity.value }}</span>
  <strong>{{ f.title }}</strong>
  <div>{{ f.category }}{% if f.cwe_id %} &middot; {{ f.cwe_id }}{% endif %}{% if f.owasp_2025 %} &middot; {{ f.owasp_2025 }}{% endif %}</div>
  {% if f.explanation %}<p class="explanation">{{ f.explanation }}</p>{% endif %}
  <details>
    <summary>Evidence ({{ f.evidence | length }})</summary>
    {% for ev in f.evidence %}
    <div class="evidence">{{ ev.url }}{% if ev.detail %} &mdash; {{ ev.detail }}{% endif %}{% if ev.snippet %}<br>{{ ev.snippet }}{% endif %}</div>
    {% endfor %}
  </details>
  <p><strong>What to do:</strong> {{ f.remediation_hint }}</p>
</div>
{% else %}
<p>No findings. Note: this does <em>not</em> prove the target is secure.</p>
{% endfor %}
<hr>
<p class="meta">Generated by VibeTest 0.1.0 &mdash; authorized targets only. This report is not a guarantee of security.</p>
</body>
</html>
"""

_env = Environment(loader=BaseLoader(), autoescape=select_autoescape(["html", "xml"]))


def render_report(result: ScanResult) -> str:
    return _env.from_string(_TEMPLATE).render(result=result)
